version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/hello-world.weenhanceit.com/html
permissions:
  - object: /var/www/hello-world.weenhanceit.com/html
    owner: ubuntu
    group: www-data
    mode: 640
    type:
      - file
  - object: /var/www/hello-world.weenhanceit.com/html
    owner: ubuntu
    group: www-data
    mode: 750
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/reload-web-server-config
      timeout: 300
      runas: root
